# Site settings
title: Kabuni
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Whole New Home Ltd (ASX: WNH) is an Australian-based company publicly traded on the ASX.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
